

from snakemake.utils import min_version

##### set minimum snakemake version #####

min_version("6.4.1")


##### setup config and necessary parameters #####


configfile: "config/config.yaml"


##### setup report #####


report: "report/workflow.rst"


##### setup singularity #####


# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
container: "docker://continuumio/miniconda3"


##### load rules #####
include: "rules/common.smk"
include: "rules/preprocess.smk"




##### Target rule ######

if config["PE"]:

    rule all:
        input:
            expand("results/fastqc/{SID}_{read}.html", SID = SAMP_NAMES, read = ['r1', 'r2'])
            expand("results/fastqc/{SID}_{read}_fastqc.zip", SID = SAMP_NAMES, read = ['r1', 'r2'])

else:

    rule all:
        input:
            expand("results/fastqc/{SID}.html", SID = SAMP_NAMES)
            expand("results/fastqc/{SID}_fastqc.zip", SID = SAMP_NAMES)

