site_name: PROseq_etal
site_url: https://proseq-etal.readthedocs.io/en/latest/
nav:
  - Introduction: index.md
  - Running PROseq_etal: deploy.md
  - PROseq_etal on Yale HPC: simon.md
  - Alternative deployment strategies: alt.md
  - Output: output.md
  - FAQs: pitfalls.md
theme: readthedocs
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets