## example of what samples will look like for fastq input
samples:
  WT_1: data/fastq/WT_1
  WT_2: data/fastq/WT_2
  WT_ctl: data/fastq/WT_ctl
  KO_1: data/fastq/KO_1
  KO_2: data/fastq/KO_2
  KO_ctl: data/fastq/KO_ctl


# Paired end?
PE: True


# Extra options to pass to fastqc
fastqc_params: "--quiet"

# Adapters to pass to fastp (not strictly necessary as fastp can autodetect)
fastp_adapters: ""

# Extra parameters for fastp
fastp_parameters: "" 