
####### PARAMETERS YOU NEED TO SET #######

## Paths to fastq containing directories.
samples:
  WT_1: data/fastq/WT_1
  WT_2: data/fastq/WT_2
  WT_ctl: data/fastq/WT_ctl
  KO_1: data/fastq/KO_1
  KO_2: data/fastq/KO_2
  KO_ctl: data/fastq/KO_ctl

## Which sample IDs are inputs/controls for others?
  # Only relevant if method == ChIPseq
controls:
  WT_1: WT_ctl
  WT_2: WT_ctl
  KO_1: KO_ctl
  KO_2: KO_ctl

### General information

# Which experiment
  # Options are: "ChIPseq" and "PROseq"
method: "PROseq"

# Paired end?
PE: True

# Strandedness
strandedness: reverse

# Path to genome fasta file
genome: data/genome/genome.fasta

# Path to annotation gtf file
annotation: data/genome/genome.gtf

# Path to pause index annotation (will be created if it does not exist)
  # Only relevant if method == PROseq
PI_gtf: data/genome/genome_PI.gtf

# Which aligner to use? 
  # Options are: "bwa-mem2", "bowtie2", "star"
aligner: "bwa-mem2"

# Path to directory containing indices
  # Indices will be built automatically if not present
  # I would suggest naming this "aligner"_index, though any
  # directory path name will do (avoid results/...; the 
  # results/ directory is where the pipeline output will be created,
  # so probably better to avoid specifying a path there that might
  # clash with the names of one of the other automatically created
  # directories). 
indices: bwamem2_index


# MACS2 callpeaks parameters
  # -f is autmoatically set to BAMPE if PE = TRUE 
  # -g determines genome size and can
callpeaks_params: "-g hs"

####### OPTIONAL PARAMETERS FOR EACH TOOL USED #######


### fastqc parameters

# Extra options to pass to fastqc
fastqc_params: "--quiet"


### fastp parameters


# Adapters to pass to fastp (not strictly necessary as fastp can autodetect)
fastp_adapters: ""

# Extra parameters for fastp
fastp_parameters: "" 


### bwa-mem2 parameters


# Do you want to automatically sort bam files produced by BWAMEM2?
  # Shouldn't be necessary as sorting is performed by pipeline automatically
bwamem2_sort: "none" # Can be 'none', 'samtools', or 'picard'

# If sorting BWA_MEM2 output, how would you like to sort it?
bwamem2_sort_order: "coordinate" # Can be 'coordinate' (default) or 'queryname'.'

# Any additional parmaters to pass to tool used for optional sorting of BWAMEM2 output
bwamem2_sort_extra: "" # Extra args for samtools/picard, relevant only if bwamem2_sort is not 'none'.

# Extra parameters to pass to bwamem2 align
bwamem2_align_params: ""


### Samtools parameters

# Optional parameters to set for samtools sort
samtools_params: ""


### bowtie2 parameters

# Optional parameters to set for bowtie2 build
bowtie2_build_params: ""

# Optional parameters to set for bowtie2 align
bowtie2_align_params: ""


### bedtools genomecov parameters

# Optional parameters to set for bedtools genomecov
genomecov_params: ""


### bedGraphToBigWig parameters

# Optional parameters to set for bedGraphtoBigWig
bg2bw_params: ""


### HOMER parameters

# Optional parameters to set for homer makeTagDir
makeTagDir_params: ""

# What peak finding style to use for homer findPeaks
  # See http://homer.ucsd.edu/homer/ngs/peaks.html for options
findPeaks_style: "groseq"

# Optional parameters to set for homer findPeaks
findPeaks_params: ""

# Optional parmaeters to set for homer mergePeaks
mergePeaks_params: "-d given"

# Mode for merging peaks
  # See http://homer.ucsd.edu/homer/ngs/mergePeaks.html for options
annotatePeaks_mode: "rna"

# Optional parameters to set for homer annotatePeaks
annotatePeaks_params: ""


### MACS2 parameters


bdgcmp_FE_params: ""
bdgcmp_diff_params: ""