## Paths to fastq containing directories.
samples:
  WT_1: data/fastq/WT_1
  WT_2: data/fastq/WT_2
  WT_ctl: data/fastq/WT_ctl
  KO_1: data/fastq/KO_1
  KO_2: data/fastq/KO_2
  KO_ctl: data/fastq/KO_ctl

## Which sample IDs are inputs/controls for others?
  # Only relevant if method == ChIPseq
controls:
  WT_1: WT_ctl
  WT_2: WT_ctl
  KO_1: KO_ctl
  KO_2: KO_ctl

### General information

# Which experiment
  # Options are: "ChIPseq" and "PROseq"
method: "PROseq"

# Paired end?
PE: True

# Strandedness
strandedness: reverse

# Path to genome fasta file
genome: data/genome/genome.fasta

# Path to annotation gtf file
annotation: data/genome/genome.gtf

# Path to pause index annotation (will be created if it does not exist)
PI_gtf: data/genome/genome_PI.gtf

# Which aligner to use? 
  # Options are: "bwa-mem2", "bowtie2", "star"
aligner: "bwa-mem2"

### fastqc parameters

# Extra options to pass to fastqc
fastqc_params: "--quiet"


### fastp parameters


# Adapters to pass to fastp (not strictly necessary as fastp can autodetect)
fastp_adapters: ""

# Extra parameters for fastp
fastp_parameters: "" 


### bwa-mem2 parameters

bwamem2_extra: ""
bwamem2_sort: "none" # Can be 'none', 'samtools', or 'picard'
bwamem2_sort_order: "coordinate"
bwamem2_sort_extra: ""


### bedtools genomecov parameters

genomecov_params: "-3"


### bedGraphToBigWig parameters

bg2bw_params: ""


### HOMER parameters

makeTagDir_params: ""

findPeaks_style: "groseq"
findPeaks_params: ""

mergePeaks_params: "-d given"

annotatePeaks_mode: "rna"
annotatePeaks_params: ""


### MACS2 parameters

callpeaks_params: "-f BAMPE -g hs"
bdgcmp_FE_params: ""
bdgcmp_diff_params: ""